# Generated by Django 4.1.3 on 2023-01-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_post_edited_on_alter_post_posted_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='edited_on',
        ),
    ]
